export const CHAPTER_FOUR_ENEMY_IDS = Object.freeze([
  "voltriz",
  "nimbarca",
  "gorjal",
  "derivante",
  "raizFulgor",
]);

export const CHAPTER_FOUR_ENEMIES = Object.freeze({
  voltriz: {
    id: "voltriz",
    label: "Voltriz",
    role: "Enxame aéreo / condutor",
    hp: 14,
    speed: 58,
    damage: 3,
    attack: "electricRanged",
    range: 3.5,
    projectileSpeed: 360,
    attackEveryMs: 1500,
    baseDamage: 6,
    threat: 7,
    color: "#22d3ee",
    scale: 0.76,
    chapterId: "chapter_04",
    airborne: true,
    movingAttackFactor: 0.22,
    resonanceMinimum: 3,
    resonanceAttackSpeedFactor: 0.85,
    windResistance: 0.25,
    canBeWindEjected: false,
    assetStates: ["flying", "attack", "death"],
    previewState: "flying",
    animationFrameMs: { flying: 85, attack: 87, death: 100 },
    attackVisual: { durationMs: 520, releaseMs: 210, muzzle: { x: 0.28, y: 0.54 }, effect: "ionicSpine" },
    description: "Predador aéreo que eletrifica uma tropa até paralisá-la e então atravessa a formação em busca do próximo alvo.",
  },
  nimbarca: {
    id: "nimbarca",
    label: "Nimbarca",
    role: "Suporte aéreo pesado",
    hp: 130,
    speed: 22,
    escortSpeed: 36,
    escortDistanceTiles: 1.5,
    maximumEscortDistanceTiles: 2.5,
    damage: 8,
    attack: "electricRanged",
    range: 2.2,
    preferredRange: 2,
    projectileSpeed: 300,
    attackEveryMs: 2800,
    baseDamage: 22,
    threat: 26,
    color: "#06b6d4",
    scale: 1.42,
    chapterId: "chapter_04",
    airborne: true,
    alliedProjectileDamageFactor: 0.8,
    selfProjectileDamageFactor: 0.9,
    movingAttackFactor: 0.3,
    shieldRadiusTiles: 2.5,
    resonancePulseEveryMs: 8000,
    resonanceCooldownFactor: 0.85,
    windResistance: 0.7,
    canBeWindEjected: false,
    assetStates: ["flying", "attack", "shieldPulse", "death"],
    previewState: "flying",
    animationFrameMs: { flying: 120, attack: 97.5, shieldPulse: 87.5, death: 100 },
    attackVisual: { durationMs: 780, releaseMs: 340, muzzle: { x: 0.35, y: 0.62 }, effect: "ventralBolt" },
    description: "Manta tempestuosa que protege e acelera o bando do mesmo pacote.",
  },
  gorjal: {
    id: "gorjal",
    label: "Gorjal",
    role: "Tanque / rompedor de formação",
    hp: 180,
    speed: 13,
    damage: 14,
    attackEveryMs: 2100,
    baseDamage: 38,
    threat: 30,
    color: "#38bdf8",
    scale: 1.55,
    chapterId: "chapter_04",
    chargeDamage: 40,
    initialChargeOnSpawn: true,
    initialChargePrepMs: 0,
    initialChargeToBase: true,
    chargePrepMs: 800,
    chargeSpeed: 230,
    chargeRange: 2,
    chargeTriggerRangeTiles: 2,
    meleeContactDistancePx: 115,
    chargeParalysisMs: 1000,
    firstChargeDelayMs: 3000,
    chargeEveryMs: 8000,
    recoverMs: 1500,
    recoverDamageTakenFactor: 1.2,
    blockedDamageFactor: 1,
    blockedStunMs: 800,
    knockbackFactor: 0.3,
    windResistance: 0.85,
    canBeWindEjected: false,
    assetStates: [
      "idle", "walking", "attack", "chargePrep", "charge", "chargeImpact",
      "recover", "stunned", "death",
    ],
    animationFrameMs: {
      idle: 170,
      walking: 105,
      attack: 95,
      chargePrep: 100,
      charge: 55,
      chargeImpact: 32.5,
      recover: 187.5,
      stunned: 105,
      death: 100,
    },
    attackVisual: { durationMs: 760, impactMs: 390 },
    description: "Blindado rompedor que entra no campo em uma investida imediata contra a primeira tropa da rota. Após o impacto, avança e combate normalmente.",
  },
  derivante: {
    id: "derivante",
    label: "Derivante",
    role: "Flanqueador / troca de rota",
    hp: 36,
    speed: 48,
    damage: 5,
    attackEveryMs: 850,
    baseDamage: 10,
    threat: 16,
    color: "#8b5cf6",
    scale: 0.96,
    chapterId: "chapter_04",
    breachCheckEveryMs: 800,
    breachCooldownMs: 3500,
    blockedThresholdMs: 900,
    jumpPrepareMs: 220,
    jumpTakeoffMs: 120,
    jumpingMs: 360,
    landingMs: 180,
    jumpForwardTiles: 1.25,
    dodgeForwardTiles: 0.6,
    coverDistanceTiles: 0.65,
    maximumJumpRows: 7,
    minimumRowScoreImprovement: 2500,
    dodgeChance: 0.35,
    dodgeCooldownMs: 4500,
    dodgeDetectionDistancePx: 150,
    jumpArcHeight: 70,
    interruptedJumpCooldownMs: 2000,
    windGlideMs: 900,
    windResistance: 0.35,
    canBeWindEjected: false,
    assetStates: [
      "idle", "walking", "attack", "jumpPrepare", "jumpTakeoff", "jumping",
      "landing", "windGlide", "stunned", "death",
    ],
    animationFrameMs: {
      idle: 125,
      walking: 75,
      attack: 53.75,
      jumpPrepare: 52.5,
      jumpTakeoff: 22.5,
      jumping: 77.5,
      landing: 40,
      windGlide: 112.5,
      stunned: 105,
      death: 100,
    },
    attackVisual: { durationMs: 430, impactMs: 190 },
    description: "Predador ágil que salta para rotas vulneráveis e explora brechas.",
  },
  raizFulgor: {
    id: "raizFulgor",
    label: "Raiz-Fulgor",
    role: "Artilharia de aterramento",
    hp: 72,
    speed: 15,
    damage: 7,
    attack: "groundingBeam",
    range: 4.5,
    preferredRange: 4,
    attackEveryMs: 2400,
    chargeMs: 700,
    baseDamage: 18,
    threat: 22,
    color: "#a855f7",
    scale: 1.18,
    chapterId: "chapter_04",
    rootingMs: 900,
    unrootingMs: 600,
    rootedDamageTakenFactor: 1.15,
    chainRadiusTiles: 1.5,
    chainDamageFactor: 0.5,
    chargedParalysisMs: 2000,
    windResistance: 0.65,
    canBeWindEjected: false,
    assetStates: [
      "idle", "walking", "rooting", "rootedIdle", "attackCharge",
      "attackRelease", "unrooting", "stunned", "death",
    ],
    animationFrameMs: {
      idle: 150,
      walking: 105,
      rooting: 112.5,
      rootedIdle: 170,
      attackCharge: 87.5,
      attackRelease: 45,
      unrooting: 75,
      stunned: 105,
      death: 100,
    },
    attackVisual: {
      chargeMs: 700,
      releaseDurationMs: 360,
      releaseMs: 700,
      aspectRatio: 1.25,
      muzzle: { x: 0.28, y: 0.28 },
      effect: "groundingBeam",
    },
    description: "Artilharia viva que se enraíza e descarrega raios em alvos eletrificados.",
  },
});

export function chapterFourAlphaMultipliers(type) {
  if (type === "voltriz") return { hp: 4.5, damage: 1.5, speed: 0.9, scale: 1.22 };
  if (type === "nimbarca") return { hp: 3, damage: 1, speed: 1, scale: 1.2 };
  if (type === "gorjal") return { hp: 3, damage: 1, speed: 1, scale: 1.2 };
  return null;
}
