const unit = (type, { count, rows, countPerRow, xOffsetTiles = 0, spawnDelayMs = 0, spawnIntervalMs = 0 } = {}) => ({
  type, ...(rows ? { rows, countPerRow } : { count }), xOffsetTiles, spawnDelayMs, spawnIntervalMs,
});

export const CHAPTER_FIVE_PACKETS = Object.freeze({
  N1: { id: "skim_school", label: "Cardume Rasante", threat: 48, weight: "light", units: [unit("mordelume", { count: 3, spawnIntervalMs: 180 })] },
  N2: { id: "rasgamar_ambush", label: "Emboscada Rasgamar", threat: 58, weight: "medium", units: [unit("enguiaRasgamar", { count: 1, xOffsetTiles: -0.7 }), unit("mordelume", { count: 2, xOffsetTiles: 0.1, spawnDelayMs: 220, spawnIntervalMs: 180 })] },
  N3: { id: "shell_screen", label: "Escudo de Carapaça", threat: 78, weight: "medium", units: [unit("carapacaNereida", { count: 1, xOffsetTiles: -0.85 }), unit("mordelume", { count: 3, xOffsetTiles: 0.1, spawnDelayMs: 260, spawnIntervalMs: 170 })] },
  N4: { id: "protected_veil", label: "Véu Protegido", threat: 64, weight: "medium", units: [unit("carapacaNereida", { count: 1, xOffsetTiles: -0.85 }), unit("medusaVeuSalino", { count: 1, xOffsetTiles: 0.7, spawnDelayMs: 260 })] },
  N5: { id: "tide_hunt", label: "Caçada de Maré", threat: 112, weight: "heavy", units: [unit("enguiaRasgamar", { rows: [1, 3], countPerRow: 1, xOffsetTiles: -0.55 }), unit("mordelume", { rows: [1, 3], countPerRow: 2, xOffsetTiles: 0.12, spawnDelayMs: 220, spawnIntervalMs: 180 })] },
  N6: { id: "regenerative_school", label: "Cardume Regenerativo", threat: 166, weight: "heavy", units: [unit("mordelume", { rows: [0, 2, 4], countPerRow: 2, spawnIntervalMs: 180 }), unit("mordelume", { rows: [1, 3], countPerRow: 1, spawnIntervalMs: 180 }), unit("medusaVeuSalino", { rows: [1, 3], countPerRow: 1, xOffsetTiles: 0.7, spawnDelayMs: 420 })] },
  N7: { id: "abyssal_column", label: "Coluna Abissal", threat: 126, weight: "heavy", units: [unit("carapacaNereida", { count: 2, xOffsetTiles: -0.85, spawnIntervalMs: 300 }), unit("mordelume", { count: 2, xOffsetTiles: 0.08, spawnDelayMs: 240, spawnIntervalMs: 180 }), unit("medusaVeuSalino", { count: 1, xOffsetTiles: 0.7, spawnDelayMs: 420 })] },
  N8: { id: "saline_siege", label: "Cerco Salino", threat: 236, weight: "heavy", units: [unit("carapacaNereida", { rows: [1, 3], countPerRow: 1, xOffsetTiles: -0.85 }), unit("enguiaRasgamar", { rows: [0, 2, 4], countPerRow: 1, xOffsetTiles: -0.52, spawnDelayMs: 180 }), unit("mordelume", { rows: [0, 1, 2, 3, 4], countPerRow: 1, xOffsetTiles: 0.08, spawnDelayMs: 260, spawnIntervalMs: 170 }), unit("mordelume", { rows: [2], countPerRow: 1, xOffsetTiles: 0.08, spawnDelayMs: 260, spawnIntervalMs: 170 }), unit("medusaVeuSalino", { rows: [1, 3], countPerRow: 1, xOffsetTiles: 0.7, spawnDelayMs: 460 })] },
  N9: { id: "nereida_convergence", label: "Convergência de Nereida", threat: 350, weight: "heavy", units: [unit("carapacaNereida", { rows: [1, 3], countPerRow: 1, xOffsetTiles: -0.85 }), unit("enguiaRasgamar", { rows: [0, 1, 2, 3, 4], countPerRow: 1, xOffsetTiles: -0.52, spawnDelayMs: 160 }), unit("mordelume", { rows: [0, 1, 2, 3, 4], countPerRow: 2, xOffsetTiles: 0.08, spawnDelayMs: 300, spawnIntervalMs: 170 }), unit("medusaVeuSalino", { rows: [1, 2, 3], countPerRow: 1, xOffsetTiles: 0.7, spawnDelayMs: 500 })] },
  N10: { id: "triphase_ambush", label: "Emboscada Trifásica", threat: 168, weight: "heavy", units: [unit("enguiaRasgamar", { rows: [0, 2, 4], countPerRow: 1, xOffsetTiles: -0.55 }), unit("mordelume", { rows: [0, 1, 2, 3, 4], countPerRow: 1, xOffsetTiles: 0.12, spawnDelayMs: 180, spawnIntervalMs: 120 }), unit("mordelume", { rows: [1], countPerRow: 1, xOffsetTiles: 0.12, spawnDelayMs: 180, spawnIntervalMs: 120 })] },
  N11: { id: "school_veil", label: "Véu do Cardume", threat: 220, weight: "heavy", units: [unit("medusaVeuSalino", { rows: [0, 2, 4], countPerRow: 1, xOffsetTiles: 0.7, spawnDelayMs: 0 }), unit("mordelume", { rows: [0, 1, 2, 3, 4], countPerRow: 2, spawnDelayMs: 400, spawnIntervalMs: 120 })] },
  N12: { id: "cross_hunt", label: "Caçada Cruzada", threat: 250, weight: "heavy", units: [unit("enguiaRasgamar", { rows: [0, 1, 3, 4], countPerRow: 1, xOffsetTiles: -0.55 }), unit("mordelume", { rows: [0, 1, 2, 3, 4], countPerRow: 1, spawnDelayMs: 180, spawnIntervalMs: 120 }), unit("mordelume", { rows: [1, 3, 4], countPerRow: 1, spawnDelayMs: 180, spawnIntervalMs: 120 }), unit("medusaVeuSalino", { rows: [1, 3], countPerRow: 1, xOffsetTiles: 0.7, spawnDelayMs: 380 })] },
  N13: { id: "abyssal_regeneration", label: "Regeneração Abissal", threat: 256, weight: "heavy", units: [unit("mordelume", { rows: [0, 1, 2, 3, 4], countPerRow: 2, spawnIntervalMs: 120 }), unit("mordelume", { rows: [1, 3], countPerRow: 1, spawnIntervalMs: 120 }), unit("medusaVeuSalino", { rows: [1, 2, 3], countPerRow: 1, xOffsetTiles: 0.7, spawnDelayMs: 360 }), unit("carapacaNereida", { rows: [1, 3], countPerRow: 1, xOffsetTiles: -0.85, spawnDelayMs: 120 })] },
  N14: { id: "five_route_siege", label: "Cerco das Cinco Rotas", threat: 410, weight: "heavy", units: [unit("enguiaRasgamar", { rows: [0, 1, 2, 3, 4], countPerRow: 1, xOffsetTiles: -0.55 }), unit("mordelume", { rows: [0, 1, 2, 3, 4], countPerRow: 2, xOffsetTiles: 0.08, spawnDelayMs: 180, spawnIntervalMs: 120 }), unit("medusaVeuSalino", { rows: [1, 2, 3], countPerRow: 1, xOffsetTiles: 0.7, spawnDelayMs: 400 }), unit("carapacaNereida", { rows: [1, 3], countPerRow: 1, xOffsetTiles: -0.85, spawnDelayMs: 100 })] },
});

export function instantiateChapterFivePacket(key, index, spawnAtMs, block = "main") {
  const source = CHAPTER_FIVE_PACKETS[key];
  if (!source) throw new Error(`Pacote desconhecido: ${key}`);
  return { id: `${source.id}_${index + 1}`, key, label: source.label, block, spawnAtMs, units: source.units.map((entry) => ({ ...entry, rows: entry.rows && [...entry.rows] })) };
}
