function freezeTheme(theme) {
  return Object.freeze({
    ...theme,
    surface: Object.freeze([...theme.surface]),
    rotation: Object.freeze({ ...theme.rotation }),
    ui: Object.freeze({ ...theme.ui }),
    lighting: Object.freeze({
      ...theme.lighting,
      keyPosition: Object.freeze([...theme.lighting.keyPosition]),
      rimPosition: Object.freeze([...theme.lighting.rimPosition]),
    }),
    world: Object.freeze({ ...theme.world }),
    planetEffects: Object.freeze({ ...theme.planetEffects }),
  });
}

export const CAMPAIGN_BIOMES = Object.freeze({
  chapter_01: freezeTheme({
    key: "hive",
    label: "Colmeia Bioluminescente",
    surface: ["#07131a", "#123d46", "#071017"],
    atmosphere: "#22d3ee",
    accent: "#f43f5e",
    light: "#e6fbff",
    ambient: "#102a31",
    fog: "#051116",
    particle: "#2dd4bf",
    cameraDistance: 4.35,
    rotation: { x: -0.16, y: 0.5, z: -0.04 },
    detail: "Colmeias, crateras e veios bioluminescentes",
    ui: {
      primary: "#22d3ee",
      secondary: "#2dd4bf",
      accent: "#fb7185",
      warning: "#f43f5e",
      panel: "rgba(3, 19, 25, .91)",
      panelAlt: "rgba(5, 35, 39, .88)",
      line: "#17616b",
      grid: "#155e75",
      glow: "rgba(34, 211, 238, .3)",
      patternOpacity: .24,
      shape: "organic",
    },
    lighting: {
      keyColor: "#e8fbff",
      keyIntensity: 1.78,
      keyPosition: [3.5, 2.4, 4.5],
      fillColor: "#59d8cf",
      fillGroundColor: "#091820",
      fillIntensity: .46,
      rimColor: "#22d3ee",
      rimIntensity: .52,
      rimPosition: [-3, .8, -3.5],
      ambientColor: "#dffaff",
      ambientIntensity: .055,
      exposure: 1.03,
      transitionSpeed: 4.8,
    },
    world: {
      fogColor: "#051116",
      fogDensityCommand: .042,
      fogDensityCampaign: .052,
      atmosphereOpacityCommand: .13,
      atmosphereOpacityCampaign: .12,
      particleOpacity: .64,
      particleSize: .017,
    },
    planetEffects: {
      kit: "hive",
      signature: "Veios vivos e esporos bioluminescentes",
      motion: .72,
    },
  }),

  chapter_02: freezeTheme({
    key: "glass",
    label: "Mar de Vidro",
    surface: ["#101329", "#415b69", "#181234"],
    atmosphere: "#7fffd4",
    accent: "#a78bfa",
    light: "#f2efff",
    ambient: "#17243b",
    fog: "#090b1b",
    particle: "#a7f3d0",
    cameraDistance: 4.5,
    rotation: { x: 0.22, y: -1.08, z: 0.08 },
    detail: "Placas cristalinas e ecos prismáticos",
    ui: {
      primary: "#a78bfa",
      secondary: "#7fffd4",
      accent: "#67e8f9",
      warning: "#f0abfc",
      panel: "rgba(10, 10, 31, .92)",
      panelAlt: "rgba(24, 18, 52, .88)",
      line: "#6d5db7",
      grid: "#4c3d84",
      glow: "rgba(167, 139, 250, .31)",
      patternOpacity: .27,
      shape: "faceted",
    },
    lighting: {
      keyColor: "#f5f3ff",
      keyIntensity: 1.68,
      keyPosition: [3.2, 2.8, 4.2],
      fillColor: "#c7e8ff",
      fillGroundColor: "#10172d",
      fillIntensity: .42,
      rimColor: "#a78bfa",
      rimIntensity: .56,
      rimPosition: [-3.2, 1.1, -3.2],
      ambientColor: "#e0f2fe",
      ambientIntensity: .05,
      exposure: 1.01,
      transitionSpeed: 4.5,
    },
    world: {
      fogColor: "#090b1b",
      fogDensityCommand: .04,
      fogDensityCampaign: .05,
      atmosphereOpacityCommand: .12,
      atmosphereOpacityCampaign: .11,
      particleOpacity: .58,
      particleSize: .017,
    },
    planetEffects: {
      kit: "glass",
      signature: "Aurora prismática e cristais orbitais",
      motion: .52,
    },
  }),

  chapter_03: freezeTheme({
    key: "chitin",
    label: "Deserto de Quitina",
    surface: ["#241209", "#9a5414", "#3c1b09"],
    atmosphere: "#f59e0b",
    accent: "#22d3ee",
    /*
     * Mantidos para compatibilidade com consumidores antigos.
     * A luz física usa o bloco lighting e permanece quase neutra.
     */
    light: "#fff4e8",
    ambient: "#211109",
    fog: "#140904",
    particle: "#d9912b",
    cameraDistance: 4.45,
    rotation: { x: -0.28, y: 2.12, z: -0.08 },
    detail: "Dunas vivas, ossadas e formações de quitina",
    ui: {
      primary: "#f59e0b",
      secondary: "#d97706",
      accent: "#22d3ee",
      warning: "#fb7185",
      panel: "rgba(22, 10, 4, .93)",
      panelAlt: "rgba(38, 21, 8, .9)",
      line: "#8a4b12",
      grid: "#6b3b10",
      glow: "rgba(245, 158, 11, .28)",
      patternOpacity: .24,
      shape: "plated",
    },
    lighting: {
      /*
       * Sol neutro quente + preenchimento azul. A identidade âmbar fica
       * no contorno, atmosfera, poeira e interface, sem amarelar a textura.
       */
      keyColor: "#fff4e8",
      keyIntensity: 1.58,
      keyPosition: [3.7, 2.8, 4.6],
      fillColor: "#bfe7f5",
      fillGroundColor: "#211109",
      fillIntensity: .43,
      rimColor: "#f97316",
      rimIntensity: .34,
      rimPosition: [-3.2, .7, -3.7],
      ambientColor: "#fffaf2",
      ambientIntensity: .045,
      exposure: .98,
      transitionSpeed: 4.2,
    },
    world: {
      fogColor: "#140904",
      fogDensityCommand: .043,
      fogDensityCampaign: .052,
      atmosphereOpacityCommand: .1,
      atmosphereOpacityCampaign: .095,
      particleOpacity: .48,
      particleSize: .016,
    },
    planetEffects: {
      kit: "chitin",
      signature: "Ossada colossal e tempestade localizada",
      motion: .9,
    },
  }),

  chapter_04: freezeTheme({
    key: "storm",
    label: "Trono da Tempestade",
    surface: ["#080b1c", "#202e54", "#090714"],
    atmosphere: "#818cf8",
    accent: "#a855f7",
    light: "#eef8ff",
    ambient: "#10172f",
    fog: "#050817",
    particle: "#67e8f9",
    cameraDistance: 4.6,
    rotation: { x: 0.3, y: -2.48, z: 0.1 },
    detail: "Cumes elétricos, ventos e tempestades distantes",
    ui: {
      primary: "#38bdf8",
      secondary: "#818cf8",
      accent: "#a855f7",
      warning: "#facc15",
      panel: "rgba(4, 8, 27, .93)",
      panelAlt: "rgba(15, 23, 54, .9)",
      line: "#354d91",
      grid: "#293a73",
      glow: "rgba(56, 189, 248, .3)",
      patternOpacity: .28,
      shape: "wind",
    },
    lighting: {
      keyColor: "#eef8ff",
      keyIntensity: 1.72,
      keyPosition: [3.1, 3, 4.1],
      fillColor: "#8fb8ff",
      fillGroundColor: "#090c21",
      fillIntensity: .4,
      rimColor: "#818cf8",
      rimIntensity: .58,
      rimPosition: [-3.4, 1.2, -3],
      ambientColor: "#dbeafe",
      ambientIntensity: .045,
      exposure: .96,
      transitionSpeed: 5.2,
    },
    world: {
      fogColor: "#050817",
      fogDensityCommand: .046,
      fogDensityCampaign: .058,
      atmosphereOpacityCommand: .13,
      atmosphereOpacityCampaign: .12,
      particleOpacity: .62,
      particleSize: .018,
    },
    planetEffects: {
      kit: "storm",
      signature: "Ciclone, detritos e descargas elétricas",
      motion: 1.12,
    },
  }),


  chapter_05: freezeTheme({
    key: "eclipse",
    label: "Eclipse Abissal",
    surface: ["#05030a", "#30104a", "#090414"],
    atmosphere: "#d946ef",
    accent: "#22d3ee",
    light: "#f5f3ff",
    ambient: "#10051c",
    fog: "#040208",
    particle: "#f0abfc",
    cameraDistance: 4.65,
    rotation: { x: .62, y: .91, z: -.12 },
    detail: "Cicatrizes do núcleo e fragmentos orbitais",
    ui: {
      primary: "#d946ef",
      secondary: "#7c3aed",
      accent: "#22d3ee",
      warning: "#fb7185",
      panel: "rgba(8, 3, 16, .94)",
      panelAlt: "rgba(31, 8, 48, .9)",
      line: "#7e22ce",
      grid: "#581c87",
      glow: "rgba(217, 70, 239, .3)",
      patternOpacity: .28,
      shape: "fractured",
    },
    lighting: {
      keyColor: "#f5f3ff",
      keyIntensity: 1.62,
      keyPosition: [3.4, 2.6, 4.3],
      fillColor: "#8be9f5",
      fillGroundColor: "#0b0614",
      fillIntensity: .38,
      rimColor: "#d946ef",
      rimIntensity: .54,
      rimPosition: [-3.4, 1.15, -3.1],
      ambientColor: "#e0e7ff",
      ambientIntensity: .04,
      exposure: .95,
      transitionSpeed: 5.4,
    },
    world: {
      fogColor: "#040208",
      fogDensityCommand: .048,
      fogDensityCampaign: .061,
      atmosphereOpacityCommand: .13,
      atmosphereOpacityCampaign: .12,
      particleOpacity: .58,
      particleSize: .018,
    },
    planetEffects: {
      kit: "eclipse",
      signature: "Cicatrizes, coroa e fragmentos orbitais",
      motion: .96,
    },
  }),
});

export const getCampaignBiome = (chapterId) =>
  CAMPAIGN_BIOMES[chapterId] || CAMPAIGN_BIOMES.chapter_01;

export const getGenesisWorldTheme = getCampaignBiome;  chapter_05: freezeTheme({
    key: "abyss",
    label: "Abismo de Nereida",
    surface: ["#03161c", "#0d4c52", "#081825"],
    atmosphere: "#22d3ee",
    accent: "#c084fc",
    light: "#cffafe",
    ambient: "#0b2835",
    fog: "#020b12",
    particle: "#5eead4",
    cameraDistance: 4.58,
    rotation: { x: -.2, y: 1.34, z: -.04 },
    detail: "Naufrágios, recifes abissais e marés bioluminescentes",
    ui: {
      primary: "#22d3ee",
      secondary: "#0e7490",
      accent: "#c084fc",
      warning: "#f59e0b",
      panel: "rgba(2, 11, 18, .94)",
      panelAlt: "rgba(6, 35, 45, .9)",
      line: "#155e75",
      grid: "#164e63",
      glow: "rgba(34, 211, 238, .28)",
      patternOpacity: .24,
      shape: "fluid",
    },
    lighting: {
      keyColor: "#cffafe",
      keyIntensity: 1.45,
      keyPosition: [3.2, 2.9, 4.1],
      fillColor: "#67e8f9",
      fillGroundColor: "#03131c",
      fillIntensity: .42,
      rimColor: "#c084fc",
      rimIntensity: .46,
      rimPosition: [-3.1, 1.05, -3.4],
      ambientColor: "#bae6fd",
      ambientIntensity: .05,
      exposure: .94,
      transitionSpeed: 5.1,
    },
    world: {
      fogColor: "#020b12",
      fogDensityCommand: .052,
      fogDensityCampaign: .064,
      atmosphereOpacityCommand: .14,
      atmosphereOpacityCampaign: .13,
      particleOpacity: .52,
      particleSize: .017,
    },
    planetEffects: {
      kit: "eclipse",
      signature: "Bruma oceânica, brilho abissal e fragmentos submersos",
      motion: .82,
    },
  }),
});

export const getCampaignBiome = (chapterId) =>
  CAMPAIGN_BIOMES[chapterId] || CAMPAIGN_BIOMES.chapter_01;

export const getGenesisWorldTheme = getCampaignBiome;  chapter_05: freezeTheme({
    key: "abyss",
    label: "Abismo de Nereida",
    surface: ["#03161c", "#0d4c52", "#081825"],
    atmosphere: "#22d3ee",
    accent: "#c084fc",
    light: "#cffafe",
    ambient: "#0b2835",
    fog: "#020b12",
    particle: "#5eead4",
    cameraDistance: 4.58,
    rotation: { x: -.2, y: 1.34, z: -.04 },
    detail: "Naufrágios, recifes abissais e marés bioluminescentes",
    ui: {
      primary: "#22d3ee",
      secondary: "#0e7490",
      accent: "#c084fc",
      warning: "#f59e0b",
      panel: "rgba(2, 11, 18, .94)",
      panelAlt: "rgba(6, 35, 45, .9)",
      line: "#155e75",
      grid: "#164e63",
      glow: "rgba(34, 211, 238, .28)",
      patternOpacity: .24,
      shape: "fluid",
    },
    lighting: {
      keyColor: "#cffafe",
      keyIntensity: 1.45,
      keyPosition: [3.2, 2.9, 4.1],
      fillColor: "#67e8f9",
      fillGroundColor: "#03131c",
      fillIntensity: .42,
      rimColor: "#c084fc",
      rimIntensity: .46,
      rimPosition: [-3.1, 1.05, -3.4],
      ambientColor: "#bae6fd",
      ambientIntensity: .05,
      exposure: .94,
      transitionSpeed: 5.1,
    },
    world: {
      fogColor: "#020b12",
      fogDensityCommand: .052,
      fogDensityCampaign: .064,
      atmosphereOpacityCommand: .14,
      atmosphereOpacityCampaign: .13,
      particleOpacity: .52,
      particleSize: .017,
    },
    planetEffects: {
      kit: "eclipse",
      signature: "Bruma oceânica, brilho abissal e fragmentos submersos",
      motion: .82,
    },
  }),
});

export const getCampaignBiome = (chapterId) =>
  CAMPAIGN_BIOMES[chapterId] || CAMPAIGN_BIOMES.chapter_01;

export const getGenesisWorldTheme = getCampaignBiome;  chapter_05: freezeTheme({
    key: "abyss",
    label: "Abismo de Nereida",
    surface: ["#03161c", "#0d4c52", "#081825"],
    atmosphere: "#22d3ee",
    accent: "#c084fc",
    light: "#cffafe",
    ambient: "#0b2835",
    fog: "#020b12",
    particle: "#5eead4",
    cameraDistance: 4.58,
    rotation: { x: -.2, y: 1.34, z: -.04 },
    detail: "Naufrágios, recifes abissais e marés bioluminescentes",
    ui: {
      primary: "#22d3ee",
      secondary: "#0e7490",
      accent: "#c084fc",
      warning: "#f59e0b",
      panel: "rgba(2, 11, 18, .94)",
      panelAlt: "rgba(6, 35, 45, .9)",
      line: "#155e75",
      grid: "#164e63",
      glow: "rgba(34, 211, 238, .28)",
      patternOpacity: .24,
      shape: "fluid",
    },
    lighting: {
      keyColor: "#cffafe",
      keyIntensity: 1.45,
      keyPosition: [3.2, 2.9, 4.1],
      fillColor: "#67e8f9",
      fillGroundColor: "#03131c",
      fillIntensity: .42,
      rimColor: "#c084fc",
      rimIntensity: .46,
      rimPosition: [-3.1, 1.05, -3.4],
      ambientColor: "#bae6fd",
      ambientIntensity: .05,
      exposure: .94,
      transitionSpeed: 5.1,
    },
    world: {
      fogColor: "#020b12",
      fogDensityCommand: .052,
      fogDensityCampaign: .064,
      atmosphereOpacityCommand: .14,
      atmosphereOpacityCampaign: .13,
      particleOpacity: .52,
      particleSize: .017,
    },
    planetEffects: {
      kit: "eclipse",
      signature: "Bruma oceânica, brilho abissal e fragmentos submersos",
      motion: .82,
    },
  }),
});

export const getCampaignBiome = (chapterId) =>
  CAMPAIGN_BIOMES[chapterId] || CAMPAIGN_BIOMES.chapter_01;

export const getGenesisWorldTheme = getCampaignBiome;
