export function buildTacticalInsights(report, { availableTroops = [], loadout = [] } = {}) {
  const insights = []; const { summary, threats, routes } = report;
  const airShare = threats.enemyDamage > 0 ? threats.airDamage / threats.enemyDamage : 0;
  if (airShare >= .35) { const hasIcaro = loadout.includes("interceptadorIcaro"); const canRecommend = availableTroops.includes("interceptadorIcaro"); insights.push({ id: "high-air-threat", priority: airShare >= .5 ? 95 : 85, severity: airShare >= .5 ? "critical" : "warning", title: "Superioridade aérea inimiga", message: `${Math.round(airShare * 100)}% do dano inimigo veio de unidades aéreas.`, recommendation: canRecommend && !hasIcaro ? "Considere utilizar Interceptador Ícaro." : "Sua composição teve baixa cobertura antiaérea.", evidence: { airDamageShare: airShare, airDamage: threats.airDamage }, ...(canRecommend && !hasIcaro ? { recommendedTroopId: "interceptadorIcaro" } : {}) }); }
  if (summary.energyGenerated > 0 && summary.energyWasted / summary.energyGenerated >= .2) insights.push({ id: "energy-waste", priority: 70, severity: "warning", title: "Energia desperdiçada", message: `${summary.energyWasted} de energia foi perdida por capacidade cheia.`, recommendation: "Implante reforços antes de atingir o limite de energia." });
  const critical = routes.find((route) => route.row === summary.mostPressuredRoute); if (critical?.averagePressure >= 55) insights.push({ id: "route-pressure", priority: 65, severity: "warning", title: "Rota sob pressão", message: `A rota ${critical.row + 1} concentrou a maior pressão inimiga.`, recommendation: "Reforce esta rota ou redistribua sua linha de frente." });
  if (summary.troopsDeployed > 0 && summary.troopsLost / summary.troopsDeployed >= .35) insights.push({ id: "high-losses", priority: 60, severity: "warning", title: "Baixas elevadas", message: `${summary.troopsLost} tropas foram perdidas na operação.`, recommendation: "Reforce a linha de frente e revise o posicionamento." });
  if (summary.objectiveDamage > summary.damageReceived && summary.objectiveDamage > 0) insights.push({ id: "objective-damage", priority: 60, severity: "warning", title: "Objetivo exposto", message: "O objetivo recebeu mais dano que as tropas.", recommendation: "Intercepte ameaças antes que atravessem a defesa." });
  return insights.sort((a, b) => b.priority - a.priority);
}
