import { CELL, FIELD } from "../visualGeometry.js";
import { getFerrivorePhaseProfile } from "./ferrivoreBiomeProfiles.js";

const C = { shadow: "#08100B", green: "#102016", floor: "#1A2518", mud: "#34281C", wet: "#463322", root: "#443523", moss: "#506238", leaf: "#74824A", rust: "#A84E2D", cyan: "#63D8C7", fog: "#15231A" };
const rgba = (hex, alpha) => { const n = Number.parseInt(String(hex).replace("#", ""), 16); return `rgba(${n >> 16 & 255},${n >> 8 & 255},${n & 255},${alpha})`; };
const seeded = (seed) => { let value = seed >>> 0; return () => { value = Math.imul(value ^ value >>> 16, 2246822519); value = Math.imul(value ^ value >>> 13, 3266489917); return ((value ^ value >>> 16) >>> 0) / 4294967296; }; };
const isFerrivore = (phase) => phase?.chapterId === "chapter_07" && phase?.battlefieldTheme?.material === "ferrivore";
const routeY = (row) => row * CELL.height + CELL.height / 2;
const nearRoute = (y, margin = 46) => Array.from({ length: FIELD.rows }, (_, row) => Math.abs(y - routeY(row)) < margin).some(Boolean);

function tree(ctx, x, y, scale, flip, random) {
  ctx.save(); ctx.translate(x, y); ctx.scale(flip, 1);
  const g = ctx.createLinearGradient(-30 * scale, 0, 30 * scale, 0); g.addColorStop(0, rgba(C.shadow, .96)); g.addColorStop(.5, rgba(C.wet, .9)); g.addColorStop(1, rgba(C.green, .6)); ctx.fillStyle = g;
  ctx.beginPath(); ctx.moveTo(-26 * scale, 0); ctx.bezierCurveTo(-35 * scale, -80 * scale, -22 * scale, -180 * scale, -8 * scale, -245 * scale); ctx.bezierCurveTo(4 * scale, -265 * scale, 22 * scale, -245 * scale, 28 * scale, -215 * scale); ctx.bezierCurveTo(14 * scale, -120 * scale, 34 * scale, -50 * scale, 48 * scale, 0); ctx.closePath(); ctx.fill();
  ctx.strokeStyle = rgba(C.root, .75); ctx.lineWidth = 4 * scale; ctx.beginPath(); ctx.moveTo(-10 * scale, 0); ctx.bezierCurveTo(-3 * scale, -100 * scale, 5 * scale, -170 * scale, 10 * scale, -225 * scale); ctx.stroke();
  ctx.fillStyle = rgba(C.moss, .6); for (let i = 0; i < 5; i += 1) { ctx.beginPath(); ctx.ellipse((random() - .5) * 70 * scale, -12 - random() * 30, 18 * scale, 5 * scale, random(), 0, Math.PI * 2); ctx.fill(); } ctx.restore();
}
function leaves(ctx, x, y, scale, random, alpha = .7) { ctx.fillStyle = rgba(random() > .5 ? C.leaf : C.moss, alpha); for (let i = 0; i < 8; i += 1) { const a = random() * Math.PI * 2; const r = (8 + random() * 20) * scale; ctx.beginPath(); ctx.ellipse(x + Math.cos(a) * r, y + Math.sin(a) * r, (9 + random() * 14) * scale, (4 + random() * 7) * scale, a, 0, Math.PI * 2); ctx.fill(); } }
function root(ctx, x, y, length, width, random) { ctx.save(); ctx.strokeStyle = rgba(C.root, .82); ctx.lineWidth = width; ctx.lineCap = "round"; ctx.beginPath(); ctx.moveTo(x, y); ctx.bezierCurveTo(x + length * .2, y - 18 - random() * 35, x + length * .72, y + 16 + random() * 28, x + length, y - 4); ctx.stroke(); ctx.strokeStyle = rgba(C.moss, .26); ctx.lineWidth = Math.max(1, width * .2); ctx.stroke(); ctx.restore(); }

export function isFerrivoreBattlefield(phase) { return isFerrivore(phase); }

export function drawFerrivoreForestBase(ctx, phase) {
  const profile = getFerrivorePhaseProfile(phase); const random = seeded((phase.battlefieldTheme?.seed || 1) + 17);
  const bg = ctx.createLinearGradient(0, 0, 0, FIELD.height); bg.addColorStop(0, C.shadow); bg.addColorStop(.42, C.green); bg.addColorStop(1, C.floor); ctx.fillStyle = bg; ctx.fillRect(0, 0, FIELD.width, FIELD.height);
  ctx.fillStyle = rgba(C.shadow, .72); for (let i = 0; i < 20; i += 1) { const x = random() * FIELD.width; const y = random() * 170; ctx.beginPath(); ctx.ellipse(x, y, 90 + random() * 110, 30 + random() * 40, random() * .4, 0, Math.PI * 2); ctx.fill(); }
  const light = ctx.createRadialGradient(FIELD.width * .48, 24, 10, FIELD.width * .48, 24, 360); light.addColorStop(0, rgba(C.leaf, .14 * (1 - profile.infestation * .22))); light.addColorStop(1, "transparent"); ctx.fillStyle = light; ctx.fillRect(0, 0, FIELD.width, FIELD.height);
  const trees = Math.round(3 + profile.giantTreeDensity * 6); for (let i = 0; i < trees; i += 1) { const side = i % 2 ? FIELD.width - 10 : 10; tree(ctx, side + (random() - .5) * 45, FIELD.height + 70, .65 + random() * .55, i % 2 ? -1 : 1, random); leaves(ctx, side + (random() - .5) * 110, 38 + random() * 90, .8 + random() * .8, random, .65); }
  ctx.fillStyle = rgba(C.wet, .2 + profile.wetness * .2); for (let i = 0; i < 44 + profile.vegetationDensity * 30; i += 1) { const x = random() * FIELD.width; const y = 8 + random() * (FIELD.height - 16); if (nearRoute(y, 52)) continue; ctx.beginPath(); ctx.ellipse(x, y, 4 + random() * 18, 2 + random() * 7, random(), 0, Math.PI * 2); ctx.fill(); }
}
export function drawFerrivoreTerrainBase(ctx, phase) { drawFerrivoreForestBase(ctx, phase); }
export function drawFerrivoreBackground(ctx, phase) { drawFerrivoreForestBase(ctx, phase); }

function lane(ctx, laneInfo, phase, profile, random) {
  const row = laneInfo.row; const center = routeY(row); const transport = row === (phase.rules?.transportRow ?? 2); const half = transport ? 40 : 27; const left = FIELD.baseX - 3; const right = FIELD.width + 8;
  ctx.save(); ctx.beginPath(); ctx.moveTo(left, center - half); ctx.bezierCurveTo(left + 180, center - half - 5, right - 200, center - half + 6, right, center - half - 3); ctx.lineTo(right, center + half + 3); ctx.bezierCurveTo(right - 220, center + half - 5, left + 170, center + half + 7, left, center + half); ctx.closePath();
  const floor = ctx.createLinearGradient(0, center - half, 0, center + half); floor.addColorStop(0, transport ? "#4A3A28" : "#26321F"); floor.addColorStop(.5, transport ? "#5A4931" : "#334226"); floor.addColorStop(1, transport ? "#30281F" : "#1B291B"); ctx.fillStyle = floor; ctx.fill(); ctx.clip();
  ctx.fillStyle = rgba(transport ? C.mud : C.moss, .18); for (let i = 0; i < (transport ? 22 : 12); i += 1) { const x = left + random() * (right - left); const y = center - half + random() * half * 2; ctx.beginPath(); ctx.ellipse(x, y, 5 + random() * 16, 1.5 + random() * 4, random(), 0, Math.PI * 2); ctx.fill(); }
  const route = phase.terrain?.routeType; if (transport && (route === "railway" || route === "industrialTrack")) { ctx.strokeStyle = rgba("#7A6A55", .55); ctx.lineWidth = 3; for (const offset of [-16, 16]) { ctx.beginPath(); ctx.moveTo(left, center + offset); ctx.lineTo(right, center + offset + 3); ctx.stroke(); } ctx.fillStyle = rgba(C.root, .5); for (let x = left + 20; x < right; x += 38) ctx.fillRect(x, center - 23 + (x % 3) * 2, 7, 46); }
  if (transport) { ctx.strokeStyle = rgba("#A88B63", .3); ctx.lineWidth = 2; ctx.setLineDash([34, 26]); ctx.beginPath(); ctx.moveTo(left, center); ctx.lineTo(right, center + 2); ctx.stroke(); ctx.setLineDash([]); }
  ctx.restore(); root(ctx, left + 35, center - half - 2, 120, transport ? 7 : 5, random); root(ctx, right - 160, center + half + 3, 130, transport ? 7 : 5, random);
}
export function drawFerrivoreCombatLanes(ctx, blueprint, phase, profile) { const random = seeded((phase.battlefieldTheme?.seed || 1) + 700); for (const laneInfo of blueprint.lanes) lane(ctx, laneInfo, phase, profile, random); }
export function drawFerrivoreConvoyRoute() { /* transport route is part of the ferrivore lane composition */ }
export function drawFerrivoreGroundVeins() { /* long cyan circuits intentionally removed */ }

export function drawFerrivoreRoots(ctx, phase) { const profile = getFerrivorePhaseProfile(phase); const random = seeded((phase.battlefieldTheme?.seed || 1) + 91); for (let i = 0; i < Math.round(10 + profile.roots * 26); i += 1) { const x = random() * FIELD.width; const y = random() < .5 ? random() * 150 : FIELD.height - random() * 150; if (nearRoute(y, 52)) continue; root(ctx, x, y, 28 + random() * 120, 2 + random() * 4, random); } }
export function drawFerrivoreGrowths(ctx, phase) { const profile = getFerrivorePhaseProfile(phase); const random = seeded((phase.battlefieldTheme?.seed || 1) + 180); for (let i = 0; i < Math.round(16 + profile.vegetationDensity * 32); i += 1) { const x = random() * FIELD.width; const y = random() * FIELD.height; if (nearRoute(y, 48)) continue; leaves(ctx, x, y, .35 + random() * .6, random, .36 + profile.vegetationDensity * .25); } drawFerrivoreRoots(ctx, phase); }
export function drawFerrivoreRuins(ctx, phase) { const profile = getFerrivorePhaseProfile(phase); const random = seeded((phase.battlefieldTheme?.seed || 1) + 501); const route = phase.terrain?.routeType || "standard"; ctx.save(); ctx.strokeStyle = rgba(C.rust, .22 + profile.ruinDensity * .18); ctx.lineWidth = 3; for (let i = 0; i < Math.round(2 + profile.ruinDensity * 7); i += 1) { const x = FIELD.baseX + 40 + random() * 900; const y = random() < .5 ? 18 + random() * 105 : FIELD.height - 18 - random() * 105; if (nearRoute(y, 54)) continue; if (route === "railway") { ctx.beginPath(); ctx.moveTo(x - 35, y); ctx.lineTo(x + 42, y + 4); ctx.stroke(); } else { ctx.strokeRect(x, y, 28 + random() * 28, 10 + random() * 18); ctx.beginPath(); ctx.moveTo(x, y); ctx.lineTo(x - 12, y - 25); ctx.stroke(); } } ctx.restore(); }
export function drawFerrivorePhaseLandmarks(ctx, phase) { const profile = getFerrivorePhaseProfile(phase); if (!profile.colonyHeart) return; ctx.save(); ctx.globalAlpha = .26; ctx.fillStyle = C.rust; ctx.beginPath(); ctx.ellipse(FIELD.width - 100, 76, 74, 46, -.2, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = C.cyan; ctx.lineWidth = 2; ctx.beginPath(); ctx.arc(FIELD.width - 100, 76, 42, 0, Math.PI * 2); ctx.stroke(); ctx.restore(); }
export function drawFerrivoreStaticDetails(ctx, phase) { drawFerrivoreGrowths(ctx, phase); drawFerrivoreRuins(ctx, phase); drawFerrivorePhaseLandmarks(ctx, phase); }
export function drawFerrivoreForeground(ctx, phase) { const random = seeded((phase.battlefieldTheme?.seed || 1) + 810); ctx.fillStyle = rgba(C.green, .8); for (let i = 0; i < 8; i += 1) { const x = random() * FIELD.width; ctx.beginPath(); ctx.ellipse(x, 4 + random() * 22, 34 + random() * 24, 5 + random() * 8, random(), 0, Math.PI * 2); ctx.fill(); } }
export function drawFerrivoreAmbient(ctx, phase, time, quality = {}, reduceMotion = false) { const profile = getFerrivorePhaseProfile(phase); const random = seeded((phase.battlefieldTheme?.seed || 1) + 330); const count = Math.round((8 + profile.spores * 28) * (quality.particles ?? 1)); const motion = reduceMotion ? 0 : time; ctx.save(); for (let i = 0; i < count; i += 1) { const x = (random() * FIELD.width + motion * .008 * (i % 2 ? 1 : -1)) % FIELD.width; const y = 30 + (random() * FIELD.height + Math.sin(motion * .0007 + i) * 12) % (FIELD.height - 50); if (nearRoute(y, 42)) continue; ctx.fillStyle = rgba(i % 4 ? C.leaf : C.cyan, .12 + profile.spores * .1); ctx.beginPath(); ctx.arc(x, y, .8 + random() * 2, 0, Math.PI * 2); ctx.fill(); } ctx.fillStyle = rgba(C.fog, .08 * profile.fogDensity); ctx.fillRect(0, 0, FIELD.width, FIELD.height); ctx.restore(); }
